name: loading_progressbar
description: "Flutter LoadingProgressbar Widget. You can pull out the progressbar Widget Whenever you want."
version: 0.0.2
repository: https://github.com/b3lon9/loading_progressbar

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^4.0.0